version: '3'
services:
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=soccerdata
      - POSTGRES_PASSWORD=admin
  # app:
  #   build: .
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - db
  #   entrypoint: npm start
